# [[plugins]]
#  call dein#add('Shougo/neosnippet.vim')
# [[plugins]]
#   call dein#add('Shougo/neosnippet-snippets')

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo ='morhetz/gruvbox'
hook_add = '''
	colorscheme gruvbox
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
	let g:airline_theme='gruvbox'
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
	map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'sheerun/vim-polyglot'


# [[plugins]]
# repo = ''

